proxy:
  build: .
  dockerfile: Dockerfile-proxy
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/nginx/vhost.d
    - /etc/nginx/certs
    - /usr/share/nginx/html
  environment:
    - DEFAULT_HOST=identitybpa.digitauxsolutions.com   
proxy-companion:
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:    
    - DEFAULT_HOST=identitybpa.digitauxsolutions.com 
  volumes_from:
    - proxy