indentitybpa:
  build: .
  dockerfile: Dockerfile-identity
  restart: always
  environment:
    - VIRTUAL_HOST=identitybpa.digitauxsolutions.com
    - LETSENCRYPT_HOST=identitybpa.digitauxsolutions.com
    - LETSENCRYPT_EMAIL=amit@digitauxsolutions.com
    - NGINX_HOST=identitybpa.digitauxsolutions.com
    - NGINX_PORT=80   
  expose:
    - 80
    - 443
